version: '3.4'

services:
  app1:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: app1
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
    ports:
       - '5000:5000'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - mynetwork


  app2:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: app2
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5001
    ports:
       - '5001:5001'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
